### ISSUE TITLE
CDN endpoint custom domain not possible

### ISSUE THREAD

**Issue by TheRSP** [CompositionalIT/farmer#474]
The template for CDN endpoint custom domains currently inserts the complete URI into the `properties.hostName` field. However, this field expects just a domain name without sceme,

```fs
endpoint { 
    custom_domain_name "https://subdomain.example.com/"; 
    // ...
}
```
Produces
```Unhandled exception. System.Exception: Deployment failed. Correlation ID: 35237319-f31c-4959-a22a-8a21c14a7809. {
  "error": {
    "code": "BadRequest",
    "message": "Property 'CustomDomain.HostName' cannot be set to 'https://subdomain.example.com/'. "
  }
}
```

Whilst attempting to provide just the domain name:

```fs
endpoint { 
    custom_domain_name "subdomain.example.com/"; 
    // ...
}
```
produces
```
Unhandled exception. System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Farmer.Builders.Cdn.EndpointBuilder.CustomDomain(EndpointConfig state, String hostname)
```

I believe the solution for this is to change `/Arm/Cdn.fs:L72`:
```diff
                member this.JsonModel =
                    {| customDomains.Create (this.Profile/this.Endpoint/this.Name, dependsOn = [ endpoints.resourceId this.Endpoint ]) with
-                        properties = {| hostName = string this.Hostname |}
+                        properties = {| hostName = string this.Hostname.Host |}
                    |} :> _
```

**Comment by isaacabraham** [comment]
@TheRSP I'm happy to push this in for 1.3 as it's a bug - just want to confirm that you've tested out this fix end-to-end to prove that it works?

**Comment by TheRSP** [comment]
I have tested the result by modifying the generated template but I haven't actually tried the modification I suggest here.

**Comment by isaacabraham** [comment]
That's fine - I'm going with a slightly different approach but will do the same thing. Thanks - will push this out this weekend.
