### ISSUE TITLE
AccessPolicy.findUsers doesn't work with azure-cli 2.34.1

### ISSUE THREAD

**Issue by forki** [CompositionalIT/farmer#884]
```
﻿﻿Unhandled exception. System.Text.Json.JsonException: 'W' is invalid after a single JSON value. Expected end of data. Path: $[1] | LineNumber: 62 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'W' is invalid after a single JSON value. Expected end of data. LineNumber: 62 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Farmer.Builders.KeyVault.findEntity@267-1.Invoke(String x)
   at Microsoft.FSharp.Core.ResultModule.Map[T,TResult,TError](FSharpFunc`2 mapping, FSharpResult`2 result) in D:\a\_work\1\s\src\fsharp\FSharp.Core\result.fs:line 9
   at Farmer.Builders.KeyVault.AccessPolicy.findEntity[a](String searchField, IEnumerable`1 values, FSharpFunc`2 searcher)
   at Farmer.Builders.KeyVault.AccessPolicy.findUsers(IEnumerable`1 emailAddresses)
   at <StartupCode$Infrastructure>.$Program.main@() in /home/gitlab-runner/builds/yy6jdAzB/0/a-team/eCarApp/infrastructure/Program.fs:line 211
```

**Comment by isaacabraham** [comment]
Oh great
